name: Docker Build and Test

on:
  push:
    branches:
      - main  # À ajuster selon votre branche principale
  pull_request:
    branches:
      - main  # À ajuster selon votre branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run container
      run: docker run -d --name myapp -p 3000:3000 myapp

    - name: Check if container is running
      run: docker ps | grep myapp

    - name: Test application
      run: |
        sleep 10  # Wait a bit for the application to start
        RESPONSE=$(curl -k -s -o /dev/null -w "%{http_code}" https://0.0.0.0:3000 || echo $?)
        if [ "$RESPONSE" -ne 60 ]; then
          echo "Unexpected response: $RESPONSE"
          exit 1
        fi
        echo "Received expected response code: $RESPONSE"

    - name: Stop and remove the container
      run: docker stop myapp && docker rm myapp
